"""empty message

Revision ID: 0d3e6a1e7f9a
Revises: 36acbb5d230f
Create Date: 2023-11-21 12:58:16.956377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3e6a1e7f9a'
down_revision = '36acbb5d230f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.alter_column('hit_dice',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.alter_column('hit_dice',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
