"""empty message

Revision ID: 312bc4c34e40
Revises: 81c1ab6c755a
Create Date: 2023-12-10 18:01:17.835913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312bc4c34e40'
down_revision = '81c1ab6c755a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('descripton', sa.String(length=255), nullable=False),
    sa.Column('range', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.String(length=255), nullable=False),
    sa.Column('components', sa.String(length=255), nullable=False),
    sa.Column('ritual', sa.Boolean(), nullable=False),
    sa.Column('concentration', sa.Boolean(), nullable=False),
    sa.Column('casting_time', sa.String(length=255), nullable=False),
    sa.Column('damage_at_slot_level', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('casting_time'),
    sa.UniqueConstraint('components'),
    sa.UniqueConstraint('concentration'),
    sa.UniqueConstraint('damage_at_slot_level'),
    sa.UniqueConstraint('descripton'),
    sa.UniqueConstraint('duration'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('range'),
    sa.UniqueConstraint('ritual')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spells')
    # ### end Alembic commands ###